services:
  - type: web
    name: dash-finance-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server -b 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9 